source 'http://rubygems.org'

gem 'rails', '~> 3'
gem 'thin'
gem 'unicorn'
gem 'bundler'
gem 'mongo'
gem 'bson'
gem 'bson_ext'
gem 'mongoid'
gem 'jquery-rails'
gem 'json'
gem 'haml'
gem 'capistrano', '2.15.5'
gem 'rvm-capistrano'
gem 'capistrano-unicorn'
gem 'less-rails-bootstrap', '2.3.3'
gem 'therubyracer', '0.10.2'
gem 'uglifier'
